export default [
  {
    id: 1,
    name: "Lemonade - Kiwi, 591 Ml",
    category: "Beauty",
    price: "$10.24",
    image: "http://dummyimage.com/230x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    name: "Ice - Clear, 300 Lb For Carving",
    category: "Shoes",
    price: "$16.11",
    image: "http://dummyimage.com/244x100.png/dddddd/000000",
  },
  {
    id: 3,
    name: "Chilli Paste, Sambal Oelek",
    category: "Jewelry",
    price: "$1.36",
    image: "http://dummyimage.com/211x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    name: "Aspic - Clear",
    category: "Computers",
    price: "$55.58",
    image: "http://dummyimage.com/219x100.png/dddddd/000000",
  },
  {
    id: 5,
    name: "Bread - White Epi Baguette",
    category: "Sports",
    price: "$76.66",
    image: "http://dummyimage.com/198x100.png/cc0000/ffffff",
  },
  {
    id: 6,
    name: "Turnip - Mini",
    category: "Industrial",
    price: "$61.05",
    image: "http://dummyimage.com/128x100.png/ff4444/ffffff",
  },
  {
    id: 7,
    name: "Icecream Bar - Del Monte",
    category: "Clothing",
    price: "$58.40",
    image: "http://dummyimage.com/153x100.png/ff4444/ffffff",
  },
  {
    id: 8,
    name: "Oven Mitts - 15 Inch",
    category: "Baby",
    price: "$86.65",
    image: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 9,
    name: "Muffin Mix - Banana Nut",
    category: "Garden",
    price: "$48.40",
    image: "http://dummyimage.com/199x100.png/cc0000/ffffff",
  },
  {
    id: 10,
    name: "Buffalo - Short Rib Fresh",
    category: "Industrial",
    price: "$85.90",
    image: "http://dummyimage.com/135x100.png/ff4444/ffffff",
  },
  {
    id: 11,
    name: "Pastry - Lemon Danish - Mini",
    category: "Shoes",
    price: "$23.89",
    image: "http://dummyimage.com/133x100.png/dddddd/000000",
  },
  {
    id: 12,
    name: "Lamb - Loin Chops",
    category: "Kids",
    price: "$18.98",
    image: "http://dummyimage.com/112x100.png/cc0000/ffffff",
  },
  {
    id: 13,
    name: "Bread - Roll, Italian",
    category: "Clothing",
    price: "$42.14",
    image: "http://dummyimage.com/121x100.png/cc0000/ffffff",
  },
  {
    id: 14,
    name: "Wine - Gato Negro Cabernet",
    category: "Automotive",
    price: "$22.26",
    image: "http://dummyimage.com/154x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    name: "Yeast Dry - Fleischman",
    category: "Jewelry",
    price: "$46.26",
    image: "http://dummyimage.com/229x100.png/dddddd/000000",
  },
  {
    id: 16,
    name: "Beef - Salted",
    category: "Baby",
    price: "$90.41",
    image: "http://dummyimage.com/220x100.png/5fa2dd/ffffff",
  },
  {
    id: 17,
    name: "Frangelico",
    category: "Industrial",
    price: "$80.70",
    image: "http://dummyimage.com/240x100.png/5fa2dd/ffffff",
  },
  {
    id: 18,
    name: "Chilli Paste, Ginger Garlic",
    category: "Home",
    price: "$71.80",
    image: "http://dummyimage.com/108x100.png/cc0000/ffffff",
  },
  {
    id: 19,
    name: "Tart Shells - Sweet, 3",
    category: "Shoes",
    price: "$51.84",
    image: "http://dummyimage.com/228x100.png/cc0000/ffffff",
  },
  {
    id: 20,
    name: "Sardines",
    category: "Kids",
    price: "$22.27",
    image: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 21,
    name: "Salsify, Organic",
    category: "Outdoors",
    price: "$17.61",
    image: "http://dummyimage.com/118x100.png/cc0000/ffffff",
  },
  {
    id: 22,
    name: "Pasta - Cappellini, Dry",
    category: "Kids",
    price: "$73.99",
    image: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
  },
  {
    id: 23,
    name: "Champagne - Brights, Dry",
    category: "Toys",
    price: "$0.20",
    image: "http://dummyimage.com/227x100.png/5fa2dd/ffffff",
  },
  {
    id: 24,
    name: "Beer - Sleeman Fine Porter",
    category: "Kids",
    price: "$49.40",
    image: "http://dummyimage.com/244x100.png/ff4444/ffffff",
  },
  {
    id: 25,
    name: "Cheese - Valancey",
    category: "Home",
    price: "$97.17",
    image: "http://dummyimage.com/230x100.png/cc0000/ffffff",
  },
  {
    id: 26,
    name: "Sugar - Brown, Individual",
    category: "Games",
    price: "$88.28",
    image: "http://dummyimage.com/188x100.png/dddddd/000000",
  },
  {
    id: 27,
    name: "Muffin - Mix - Mango Sour Cherry",
    category: "Jewelry",
    price: "$2.33",
    image: "http://dummyimage.com/157x100.png/5fa2dd/ffffff",
  },
  {
    id: 28,
    name: "Cod - Fillets",
    category: "Books",
    price: "$71.45",
    image: "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
  },
  {
    id: 29,
    name: "Table Cloth 90x90 White",
    category: "Books",
    price: "$92.75",
    image: "http://dummyimage.com/167x100.png/5fa2dd/ffffff",
  },
  {
    id: 30,
    name: "Ice Cream - Vanilla",
    category: "Toys",
    price: "$84.48",
    image: "http://dummyimage.com/107x100.png/ff4444/ffffff",
  },
];
